# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genre',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], default='-----', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('ASISTENTE', 'Asistente'), ('PONENTE', 'Ponente'), ('AMBOS', 'Ambos')], default='ASISTENTE', max_length=10),
        ),
    ]
